#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_varnish4(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(cmk.paths.local_agents_dir + "/plugins/varnish4", plugins_dir + "/varnish4")

bakery_info["varnish4"] = {
    "bake_function" : bake_varnish4,
    "os"            : [ "linux", ],
}
