#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2017 Precedent Communications
#          Robertas Reiciunas <robertas.reiciunas@precedent.com>

def bake_proxmox_qemu(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(cmk.paths.local_agents_dir + "/plugins/proxmox_qemu", plugins_dir + "/proxmox_qemu")

bakery_info["proxmox_qemu"] = {
    "bake_function" : bake_proxmox_qemu,
    "os"            : [ "linux", ],
}

